[package]
name = "typit-matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
dirs = "6.0.0"
dotenvy = "0.15.7"
matrix-sdk = "0.16.0"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49", features = ["full"] }
